global using Shared.DDD;
global using Catalog.Features.Products.Domain;
global using Catalog.Features.Products.Events;
global using Microsoft.EntityFrameworkCore;
global using Shared.CQRS;
global using Catalog.Persistence;
global using Catalog.Features.Products.Dtos;
global using Mapster;
global using Microsoft.Extensions.Logging;